import "./Event";
import "./User";
import "./Event";
import "./PaymentOrder";
import "./College";
import "./Branch";
import "./Organizer";
import "./BranchRep";
import "./Round";
import "./Team";
import "./Judge";
import "./Criteria";
import "./Score";
import "./Winner";
import "./Submission";
import "./Card";
import "./ProniteRegistration";
import "./XP"
import "./Level"
import "./Quiz"
import "./Question"
import "./Options"
import "./MCQSubmission"
import "./FITBSubmission"
import "./LASubmission"
import "./UserInHotel"
import "./Hotel"
import "./QuizSubmissions"
